### ISSUE TITLE
Class 'NotificationEmail' not found

### ISSUE THREAD

**Issue by MarcelWeidum** [barrelstrength/craft-sprout-email#116]
### Description
When i try to send a test notification:

`2019-05-14 10:02:52 [-][1][-][error][Error] Error: Class 'barrelstrength\sproutbase\app\email\elements\NotificationEmail' not found in /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/craftcms/cms/src/services/Elements.php:211
Stack trace:
#0 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/barrelstrength/sprout-base-email/src/controllers/MailersController.php(27): craft\services\Elements->getElementById(3092)
#1 [internal function]: barrelstrength\sproutbaseemail\controllers\MailersController->actionGetPrepareModal()
#2 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('get-prepare-mod...', Array)
#5 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-prepare-mod...', Array)
#6 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('sprout-base-ema...', Array)
#7 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('sprout-base-ema...', Array)
#8 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /var/www/vhosts/health2work.nl/new.health2work.nl/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/vhosts/health2work.nl/new.health2work.nl/web/index.php(21): yii\base\Application->run()`

### Steps to reproduce

1. Make form
2. Make notification for form
3. Try to send test notification

### Additional info

- Craft version: 3.1.26
- PHP version: 7.2.17
- Database driver & version: MySQL 5.5.5
- Plugins & versions: -

**Comment by BenParizek** [comment]
@MarcelWeidum Can you share the specific versions of the Sprout plugins you are using and any steps you may have taken recently around updating Craft or the plugins?

The error message is referring to a class that no longer exists in the most recent version of our plugins so the fix here will probably just be to get you updated to the latest.

Let me know if updating to the latest solves the issue or please post more info about specific version details and I can try to offer a more specific path to resolution.

**Comment by MarcelWeidum** [comment]
@BenParizek 3.0.0-beta.56

**Comment by BenParizek** [comment]
@MarcelWeidum That version number looks like a Sprout Forms version number so I'll assume that you only have Sprout Forms installed. If you have any other Sprout plugins installed, that may change my response.

Can you also share any steps you may have taken recently around updating Craft or the plugins? The issue is likely that the wrong version of a Sprout dependency is installed, so understanding how you are updating things would help troubleshoot that.

If you're comfortable with composer, you can try:

```
composer remove barrelstrength/sprout-forms
composer require barrelstrength/sprout-forms:3.0.0-beta.57
```

**Comment by MarcelWeidum** [comment]
@BenParizek i have installed `"barrelstrength/sprout-forms": "3.0.0-beta.57"` but still the same error. I have no other plugins, I tried it on a clean craft install

**Comment by BenParizek** [comment]
@MarcelWeidum Can you describe the steps you are taking to upgrade? Are you doing it via composer or the control panel? Can you share your full composer.json file?

For some reason, whatever you have installed is trying to access something that no longer exists in our plugins. The file `barrelstrength\sproutbase\app\email\elements\NotificationEmail` does not exist in the most recent version of our plugin. If you're still getting the error from your first message, it suggests that something did not get upgraded properly or an installation didn't overwrite an older or cached version of the plugin and its dependencies.

If we can't track down what's going on here, can you ping me on Craft Discord (BenParizek) or grab a time on my calendar and we can troubleshoot in real time:
https://calendly.com/benparizek
