### ISSUE TITLE
Issue when logging email errors from console request

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#32]
Fred says:

Should add a check in there for when its running inside of a console job
So that it doesn’t try to fetch properties that isn’t available
Same when you log the success event

```
PHP Error[8]: Undefined index: REMOTE_ADDR
	    in file /srv/users/serverpilot/apps/websitefolder/craft/app/services/HttpRequestService.php at line 1119
	#0 /srv/users/serverpilot/apps/websitefolder/craft/app/etc/console/ConsoleApp.php(265): Craft\ConsoleApp->handleError()
	#1 /srv/users/serverpilot/apps/websitefolder/craft/app/services/HttpRequestService.php(1119): Craft\ConsoleApp->handleError()
	#2 /srv/users/serverpilot/apps/websitefolder/craft/app/services/HttpRequestService.php(1047): Craft\HttpRequestService->getIpAddress()
	#3 /srv/users/serverpilot/apps/websitefolder/craft/plugins/sproutemail/services/SproutEmail_SentEmailsService.php(39): Craft\HttpRequestService->getUserHostAddress()
	#4 /srv/users/serverpilot/apps/websitefolder/craft/plugins/sproutemail/services/SproutEmailService.php(673): Craft\SproutEmail_SentEmailsService->logSentEmail()
	#5 /srv/users/serverpilot/apps/websitefolder/craft/plugins/sproutemail/SproutEmailPlugin.php(230): Craft\SproutEmailService->handleLogSentEmailOnSendEmailError()
	#6 /srv/users/serverpilot/apps/websitefolder/craft/app/framework/base/CComponent.php(567): Craft\SproutEmailPlugin->Craft\{closure}()
	#7 /srv/users/serverpilot/apps/websitefolder/craft/app/services/EmailService.php(239): Craft\EmailService->raiseEvent()
	#8 /srv/users/serverpilot/apps/websitefolder/craft/app/services/EmailService.php(482): Craft\EmailService->onSendEmailError()
	#9 /srv/users/serverpilot/apps/websitefolder/craft/app/services/EmailService.php(77): Craft\EmailService->_sendEmail()
	#10 /srv/users/serverpilot/apps/websitefolder/craft/plugins/subscribe/services/Subscribe_EmailService.php(61): Craft\EmailService->sendEmail()
	#11 /srv/users/serverpilot/apps/websitefolder/craft/plugins/subscribe/consolecommands/SubscribeCommand.php(86): Craft\Subscribe_EmailService->sendEmail()
	#12 unknown(0): Craft\SubscribeCommand->actionSend()
	#13 /srv/users/serverpilot/apps/websitefolder/craft/app/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs()
	#14 /srv/users/serverpilot/apps/websitefolder/craft/app/framework/console/CConsoleCommandRunner.php(71): Craft\SubscribeCommand->run()
	#15 /srv/users/serverpilot/apps/websitefolder/craft/app/framework/console/CConsoleApplication.php(92): Craft\ConsoleCommandRunner->run()
	#16 /srv/users/serverpilot/apps/websitefolder/craft/app/framework/base/CApplication.php(185): Craft\ConsoleApp->processRequest()
	#17 /srv/users/serverpilot/apps/websitefolder/craft/app/etc/console/yiic.php(89): Craft\ConsoleApp->run()
	#18 /srv/users/serverpilot/apps/websitefolder/craftstaging(5): require_once()```

**Comment by pdaleramirez** [comment]
Committed fix here https://github.com/barrelstrength/craft-sprout-email/commit/5bcbea24cc198450b962f9c407ce398b15bb31b6
